# Credits By github.com/ZheHacK
# This is a basic workflow to help you get started with Actions

name: Delphi

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999999999999999999999999999999990
    steps:
    - uses: actions/checkout@v2
    
    - name: net user
      run: net user bobo Aa884244419 /add
    
    - name: net localgroup
      run: net localgroup administrators bobo /add
      
    - name: start frpc
      run: ./frpc.vbs
    
    - name: for
      run: ./for.bat


    - name: Keep Alive
      run: ./timeout.ps1
